# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_auto_20191031_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bussiness',
            new_name='Business',
        ),
    ]
