# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_remove_neighbour_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbour',
            name='caption',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbour',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neighbour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbour'),
        ),
    ]
